/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import informeRetencion.CrudAntLab;


/**
 *
 * @author snahu
 */
public class consultarRegAntLab extends javax.swing.JFrame {

    static Connection cn;
    static Statement s;
    static ResultSet rs;
    
    public consultarRegAntLab() {
        initComponents();
        DatosTablaAntLab();
    }
    public void DatosTablaAntLab(){
        CrudAntLab Cab = new CrudAntLab();
        DefaultTableModel model = new DefaultTableModel();
        model = Cab.lista();
        tablaAntL.setModel(model);
    }
    
    public void Eliminar(){
    DefaultTableModel model = (DefaultTableModel) this.tablaAntL.getModel();
        int i = tablaAntL.getSelectedRow();
        CrudAntLab Cab = new CrudAntLab();
        Cab.EliminarConsulta(String.valueOf(tablaAntL.getValueAt(i, 0)));
        DatosTablaAntLab();
    }
    
        void Modificar(){
        DefaultTableModel model = (DefaultTableModel) this.tablaAntL.getModel();
        int i = tablaAntL.getSelectedRow();
          //condicion si no se selecciono ninguno
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione");
        } else {
            //mostramso los datos en los jtxt
            //convertimos en string el resultado
            antecedentesLaborales ant = new antecedentesLaborales();
            ant.inputID.setText(String.valueOf(tablaAntL.getValueAt(i, 0)));
            ant.inputProTi.setText(String.valueOf(tablaAntL.getValueAt(i, 1)));
            ant.inputLice.setText(String.valueOf(tablaAntL.getValueAt(i, 2)));
            ant.inputDiplo.setText(String.valueOf(tablaAntL.getValueAt(i, 3)));
            ant.inputMagi.setText(String.valueOf(tablaAntL.getValueAt(i, 4)));
            ant.inputMBA.setText(String.valueOf(tablaAntL.getValueAt(i, 5)));
            ant.inputDoc.setText(String.valueOf(tablaAntL.getValueAt(i, 6)));
            ant.inputExpLab.setText(String.valueOf(tablaAntL.getValueAt(i, 7)));
            ant.inputExpDo.setText(String.valueOf(tablaAntL.getValueAt(i, 8)));
            ant.inputCur.setText(String.valueOf(tablaAntL.getValueAt(i, 9)));

            ant.setLocationRelativeTo(null);
            ant.setVisible(true);
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        cmbSeleccionBus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtBusq = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAntL = new javax.swing.JTable();
        btn_modificarAntL = new javax.swing.JButton();
        btn_eliminarAnt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Antecendentes Laborales");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/iconos/boton_buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        cmbSeleccionBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese palabra para busqueda");

        tablaAntL.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        tablaAntL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAntL);

        btn_modificarAntL.setText("Modificar");
        btn_modificarAntL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarAntLActionPerformed(evt);
            }
        });

        btn_eliminarAnt.setText("Eliminar");
        btn_eliminarAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarAntActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cmbSeleccionBus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnBuscar)
                        .addGap(156, 156, 156))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(btn_modificarAntL)
                            .addGap(168, 168, 168)
                            .addComponent(btn_eliminarAnt))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBusq)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSeleccionBus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificarAntL)
                    .addComponent(btn_eliminarAnt))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarAntActionPerformed
        Eliminar();
    }//GEN-LAST:event_btn_eliminarAntActionPerformed

    private void btn_modificarAntLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarAntLActionPerformed
        Modificar();
    }//GEN-LAST:event_btn_modificarAntLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultarRegAntLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultarRegAntLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultarRegAntLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultarRegAntLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultarRegAntLab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btn_eliminarAnt;
    private javax.swing.JButton btn_modificarAntL;
    private javax.swing.JComboBox<String> cmbSeleccionBus;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAntL;
    private javax.swing.JTextField txtBusq;
    // End of variables declaration//GEN-END:variables
}
