/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.alee.laf.WebLookAndFeel;
import java.awt.print.PrinterException;
import java.io.File;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.CRUDjustificacion;
import modelo.ModeloExcel;
import modelo.justificacion;

/**
 *
 * @author Lenovo-W530
 */
public class justificacionInasistencia extends javax.swing.JFrame {

    /**
     * Creates new form justificacionInasistencia
     */
    public justificacionInasistencia() {
        initComponents();
        DatosTabla();
       
    }

    public void cargarjustificacion(String id_justificacion) {
        CRUDjustificacion just = new CRUDjustificacion();
        String[] lista = new String[6];
        lista = just.cargarjustificacion(id_justificacion);
        this.inputId.setText(lista[0]);
        this.inputNombre.setText(lista[1]);
        this.inputHorario.setText(lista[2]);
        this.inputSeccion.setText(lista[3]);
        this.inputJornada.setSelectedItem(lista[4]);
        this.inputIncidente.setText(lista[5]);
        this.inputComentario.setText(lista[6]);
    }
      
    
    public void DatosTabla(){
     
        CRUDjustificacion just = new CRUDjustificacion();
        DefaultTableModel model = new DefaultTableModel();
        model = just.lista("");
        Tabla1.setModel(model);
    }
    
      public void Agregar() {
        CRUDjustificacion just = new CRUDjustificacion();
        just.AgregarConsulta(inputNombre.getText(), inputHorario.getText(), inputSeccion.getText(), inputJornada.getSelectedItem().toString(), inputIncidente.getText(), inputComentario.getText());
    }

    public void Eliminar() {
        CRUDjustificacion just = new CRUDjustificacion();
        just.EliminarConsulta(inputId.getText());
    }

    public void Modificar() {
        CRUDjustificacion just = new CRUDjustificacion();
        //en el mismo orden que el metodo en operaciones
       just.ModificarConsulta(inputNombre.getText(), inputHorario.getText(), inputSeccion.getText(), inputJornada.getSelectedItem().toString(), inputIncidente.getText(), inputComentario.getText(), inputId.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputHorario = new javax.swing.JTextField();
        inputSeccion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        inputIncidente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        inputComentario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        inputJornada = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 815));
        setPreferredSize(new java.awt.Dimension(1100, 815));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE JUSTIFICACIÓN DE INASISTENCIA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 30, 529, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nombre de Docente:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 160, 150, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Horario del curso:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 210, 130, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Sección:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 250, 60, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Jornada:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 290, 70, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Comentario:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 390, 90, 17);

        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        getContentPane().add(inputNombre);
        inputNombre.setBounds(210, 160, 150, 20);

        inputHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(inputHorario);
        inputHorario.setBounds(210, 210, 150, 20);

        inputSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSeccionActionPerformed(evt);
            }
        });
        getContentPane().add(inputSeccion);
        inputSeccion.setBounds(210, 250, 150, 20);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 540, 452, 240);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 480, 1100, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 80, 600, 2);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(600, 82, 10, 400);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(600, 80, 450, 2);

        inputIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIncidenteActionPerformed(evt);
            }
        });
        getContentPane().add(inputIncidente);
        inputIncidente.setBounds(210, 340, 150, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(207, 15, 15));
        jLabel5.setText("INASISTENCIAS REGISTRADAS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 490, 244, 20);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(207, 15, 15));
        jLabel9.setText("Opciones Habilitadas");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(750, 100, 147, 19);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Incidente:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 340, 70, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/voliendo.png"))); // NOI18N
        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(870, 20, 170, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-multiedición-40.png"))); // NOI18N
        jButton2.setText("Ingresar Justificación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(721, 140, 210, 50);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-editar-archivo-40.png"))); // NOI18N
        jButton3.setText("Modificar Justificación");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(720, 200, 210, 50);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-eliminar-archivo-40.png"))); // NOI18N
        jButton4.setText("Eliminar Justificación");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(720, 260, 210, 50);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/goma.png"))); // NOI18N
        jButton5.setText("Limpiar Campos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 320, 210, 50);

        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-actualizar-40.png"))); // NOI18N
        jButton6.setText("Actualizar Registros");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(720, 380, 210, 50);

        inputComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputComentarioActionPerformed(evt);
            }
        });
        getContentPane().add(inputComentario);
        inputComentario.setBounds(210, 390, 150, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Id:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 120, 30, 16);

        inputId.setEnabled(false);
        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });
        getContentPane().add(inputId);
        inputId.setBounds(210, 120, 150, 20);

        inputJornada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Jornada:", "Diurna", "Tarde", "Vespertina" }));
        getContentPane().add(inputJornada);
        inputJornada.setBounds(210, 290, 150, 21);

        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-ms-excel-48.png"))); // NOI18N
        jButton7.setText("Exportar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(870, 540, 133, 40);

        jButton8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-maquina-de-copiar-40.png"))); // NOI18N
        jButton8.setText("Imprimir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(870, 640, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/Wallpaper3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1160, 840);

        setSize(new java.awt.Dimension(1116, 854));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
           this.setVisible(false);
dashboardAdmin dash = new dashboardAdmin ();
   dash.setVisible(true);
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Agregar();
        DatosTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Modificar();
        DatosTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Eliminar();
        DatosTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      this.inputId.setText("");
        this.inputNombre.setText("");
        this.inputHorario.setText("");
        this.inputSeccion.setText("");
        this.inputJornada.setSelectedIndex(0);
        this.inputIncidente.setText("");
        this.inputComentario.setText("");
       
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DatosTabla();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHorarioActionPerformed

    private void inputSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSeccionActionPerformed

    private void inputIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIncidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIncidenteActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        
        
        DefaultTableModel model = (DefaultTableModel) this.Tabla1.getModel();
               int i = Tabla1.getSelectedRow();
               //condicion si no se selecciono ninguno
               if (i == -1) {
               JOptionPane.showMessageDialog(this, "Seleccione");
              } else {
              //mostramso los datos en los jtxt
              //convertimos en string el resultado
              inputId.setText(String.valueOf(Tabla1.getValueAt(i, 0)));
            inputNombre.setText(String.valueOf(Tabla1.getValueAt(i, 1)));
            inputHorario.setText(String.valueOf(Tabla1.getValueAt(i, 2)));
            inputSeccion.setText(String.valueOf(Tabla1.getValueAt(i, 3)));
            inputJornada.setSelectedItem(String.valueOf(Tabla1.getValueAt(i, 4)));
            inputIncidente.setText(String.valueOf(Tabla1.getValueAt(i, 5)));
            inputComentario.setText(String.valueOf(Tabla1.getValueAt(i,6)));
           
        }
        

    }//GEN-LAST:event_Tabla1MouseClicked

    private void inputComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputComentarioActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                   JFileChooser fc = new JFileChooser();
                int option = fc.showSaveDialog(Tabla1);
                if(option == JFileChooser.APPROVE_OPTION){
                    String filename = fc.getSelectedFile().getName(); 
                    String path = fc.getSelectedFile().getParentFile().getPath();

					int len = filename.length();
					String ext = "";
					String file = "";

					if(len > 6){
						ext = filename.substring(len-4, len);
					}

					if(ext.equals(".xls")){
						file = path + "\\" + filename; 
					}else{
						file = path + "\\" + filename + ".xls"; 
					}
					//toExcel
                                        ModeloExcel me = new ModeloExcel();
                                        me.Exportar(new File(file),Tabla1);
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       
        MessageFormat format = new MessageFormat("Justificaciones de Inasistencias de Docentes: Page - {0}");
        MessageFormat format2 = new MessageFormat("CHSCRUM");
        try {
            Tabla1.print(JTable.PrintMode.FIT_WIDTH, format, format2);
        } catch (PrinterException ex) {
            Logger.getLogger(RegistroDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(WebLookAndFeel.class.getCanonicalName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(justificacionInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(justificacionInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(justificacionInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(justificacionInasistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new justificacionInasistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTextField inputComentario;
    private javax.swing.JTextField inputHorario;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputIncidente;
    private javax.swing.JComboBox<String> inputJornada;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputSeccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

}
