/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.alee.laf.WebLookAndFeel;
import java.awt.print.PrinterException;
import java.io.File;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.ModeloExcel;
import proyectoING.CrudAntDocente;


public class RegistroDocente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDocente
     */
    public RegistroDocente() {
        initComponents();
        DatosTabla();
        this.inputID.setEnabled(false);
    }

        public void DatosTabla() {
        CrudAntDocente Caa = new CrudAntDocente();
        DefaultTableModel model = new DefaultTableModel();
        model = Caa.lista();
        Tabla1.setModel(model);
    }

    public void Agregar() {
        CrudAntDocente Caa = new CrudAntDocente();
        Caa.AgregarConsulta(inputNC.getText(), inputN.getText(), inputAP.getText(), inputAM.getText(),inputFN.getText() ,inputNT.getText() ,inputD.getText(), inputCE.getText(), inputAI.getText(), inputINC.getText(), inputTEC.getText());
    }

    //metodo para eliminar datos
    public void Eliminar() {
        CrudAntDocente Caa = new CrudAntDocente();
        Caa.EliminarConsulta(inputID.getText());
    }

    //metodo para modificar datos
    public void Modificar() {
        CrudAntDocente Caa = new CrudAntDocente();
        //en el mismo orden que el metodo en operaciones
        Caa.ModificarConsulta(inputNC.getText(), inputN.getText(), inputAP.getText(), inputAM.getText(), inputFN.getText(), inputNT.getText() ,inputD.getText(), inputCE.getText(), inputAI.getText(), inputINC.getText(), inputTEC.getText(), inputID.getText());
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputNC = new javax.swing.JTextField();
        inputN = new javax.swing.JTextField();
        inputAP = new javax.swing.JTextField();
        inputAM = new javax.swing.JTextField();
        inputFN = new javax.swing.JTextField();
        inputD = new javax.swing.JTextField();
        inputCE = new javax.swing.JTextField();
        inputAI = new javax.swing.JTextField();
        inputINC = new javax.swing.JTextField();
        inputTEC = new javax.swing.JTextField();
        inputNT = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnEli = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        btnLimpiarCamp = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1163, 800));
        setPreferredSize(new java.awt.Dimension(1163, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setText("ANTECEDENTES PERSONALES DEL DOCENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 490, 31);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 180, 20, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Número de cedula:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 220, 140, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 260, 60, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Apellido Paterno:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 310, 120, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Apellido Materno:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 360, 130, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/PERSONA NORMAL.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 70, 40, 50);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 400, 160, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Dirección:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 220, 80, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Correo Electronico:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 260, 140, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Año de ingreso:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 310, 111, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Inicio de Contrato:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 360, 140, 17);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(207, 15, 15));
        jLabel14.setText("Opciones habilitadas:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(880, 150, 192, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel15.setText("DOCENTES REGISTRADOS");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 490, 283, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Termino de Contrato:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(430, 400, 150, 17);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Número Teléfonico:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(440, 180, 140, 14);

        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });
        getContentPane().add(inputID);
        inputID.setBounds(210, 180, 150, 20);

        inputNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNCActionPerformed(evt);
            }
        });
        getContentPane().add(inputNC);
        inputNC.setBounds(210, 220, 150, 20);

        inputN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNActionPerformed(evt);
            }
        });
        getContentPane().add(inputN);
        inputN.setBounds(210, 260, 150, 20);

        inputAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAPActionPerformed(evt);
            }
        });
        getContentPane().add(inputAP);
        inputAP.setBounds(210, 310, 150, 20);

        inputAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAMActionPerformed(evt);
            }
        });
        getContentPane().add(inputAM);
        inputAM.setBounds(210, 360, 150, 20);

        inputFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFNActionPerformed(evt);
            }
        });
        getContentPane().add(inputFN);
        inputFN.setBounds(210, 400, 150, 20);

        inputD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDActionPerformed(evt);
            }
        });
        getContentPane().add(inputD);
        inputD.setBounds(600, 220, 150, 20);

        inputCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCEActionPerformed(evt);
            }
        });
        getContentPane().add(inputCE);
        inputCE.setBounds(600, 260, 150, 20);

        inputAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAIActionPerformed(evt);
            }
        });
        getContentPane().add(inputAI);
        inputAI.setBounds(600, 310, 150, 20);

        inputINC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputINCActionPerformed(evt);
            }
        });
        getContentPane().add(inputINC);
        inputINC.setBounds(600, 360, 150, 20);

        inputTEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTECActionPerformed(evt);
            }
        });
        getContentPane().add(inputTEC);
        inputTEC.setBounds(600, 400, 150, 20);

        inputNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNTActionPerformed(evt);
            }
        });
        getContentPane().add(inputNT);
        inputNT.setBounds(600, 180, 150, 20);

        btnAgregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/agregarflex.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(880, 190, 190, 40);

        btnMod.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/modificarflex.png"))); // NOI18N
        btnMod.setText("MODIFICAR");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });
        getContentPane().add(btnMod);
        btnMod.setBounds(880, 250, 190, 40);

        btnEli.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/eliminarflex.png"))); // NOI18N
        btnEli.setText("ELIMINAR");
        btnEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliActionPerformed(evt);
            }
        });
        getContentPane().add(btnEli);
        btnEli.setBounds(880, 310, 190, 40);

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/encontrarflex.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(880, 370, 190, 40);

        btnMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/voliendo.png"))); // NOI18N
        btnMenu.setText("VOLVER AL MENÚ");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(860, 70, 220, 40);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 550, 1090, 230);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 130, 750, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 440, 750, 2);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 130, 20, 310);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(780, 130, 20, 310);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(820, 130, 300, 2);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(820, 440, 300, 2);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(820, 130, 10, 310);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(1120, 130, 10, 310);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(820, 40, 300, 20);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(820, 40, 10, 100);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator11);
        jSeparator11.setBounds(1120, 40, 10, 90);

        btnLimpiarCamp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpiarCamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/goma.png"))); // NOI18N
        btnLimpiarCamp.setText("Limpiar Campos");
        btnLimpiarCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCampActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarCamp);
        btnLimpiarCamp.setBounds(860, 450, 230, 40);
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(820, 500, 300, 10);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator13);
        jSeparator13.setBounds(820, 440, 10, 60);

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator14);
        jSeparator14.setBounds(1120, 440, 10, 60);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-ms-excel-48.png"))); // NOI18N
        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 480, 140, 50);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/icons8-maquina-de-copiar-40.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 480, 130, 49);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazIconos/Wallpaper3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1170, 820);

        setSize(new java.awt.Dimension(1179, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Agregar();
        DatosTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
       dashboardAdmin frm = new dashboardAdmin();

        frm.setLocationRelativeTo(null);
        frm.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
      Modificar();
      DatosTabla();
    }//GEN-LAST:event_btnModActionPerformed

    private void btnEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliActionPerformed
        Eliminar();
        DatosTabla();
    }//GEN-LAST:event_btnEliActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDocente frm = new buscarDocente();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void inputINCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputINCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputINCActionPerformed

    private void inputTECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTECActionPerformed

    private void inputAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAIActionPerformed

    private void inputCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCEActionPerformed

    private void inputDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDActionPerformed

    private void inputNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNTActionPerformed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void inputNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNCActionPerformed

    private void inputNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNActionPerformed

    private void inputAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAPActionPerformed

    private void inputAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAMActionPerformed

    private void inputFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFNActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
               DefaultTableModel model = (DefaultTableModel) this.Tabla1.getModel();
               int i = Tabla1.getSelectedRow();
               //condicion si no se selecciono ninguno
               if (i == -1) {
               JOptionPane.showMessageDialog(this, "Seleccione");
              } else {
              //mostramso los datos en los jtxt
              //convertimos en string el resultado
            inputID.setText(String.valueOf(Tabla1.getValueAt(i, 0)));
            inputNC.setText(String.valueOf(Tabla1.getValueAt(i, 1)));
            inputN.setText(String.valueOf(Tabla1.getValueAt(i, 2)));
            inputAP.setText(String.valueOf(Tabla1.getValueAt(i, 3)));
            inputAM.setText(String.valueOf(Tabla1.getValueAt(i, 4)));
            inputFN.setText(String.valueOf(Tabla1.getValueAt(i,5)));
            inputNT.setText(String.valueOf(Tabla1.getValueAt(i, 6)));
            inputD.setText(String.valueOf(Tabla1.getValueAt(i, 7)));
            inputCE.setText(String.valueOf(Tabla1.getValueAt(i, 8)));
            inputAI.setText(String.valueOf(Tabla1.getValueAt(i, 9)));
            inputINC.setText(String.valueOf(Tabla1.getValueAt(i, 10)));
            inputTEC.setText(String.valueOf(Tabla1.getValueAt(i, 11)));
        }
      
    }//GEN-LAST:event_Tabla1MouseClicked

    private void btnLimpiarCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCampActionPerformed
         this.inputID.setText("");
        this.inputNC.setText("");
        this.inputN.setText("");
        this.inputAP.setText("");
        this.inputAM.setText("");
        this.inputFN.setText("");
        this.inputNT.setText("");
        this.inputD.setText("");
        this.inputCE.setText("");
        this.inputAI.setText(""); 
        this.inputINC.setText("");
        this.inputTEC.setText(""); 
    }//GEN-LAST:event_btnLimpiarCampActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MessageFormat format = new MessageFormat("Antecedentes de Docentes: Page - {0}");
        MessageFormat format2 = new MessageFormat("CHSCRUM");
        try {
            Tabla1.print(JTable.PrintMode.FIT_WIDTH, format, format2);
        } catch (PrinterException ex) {
            Logger.getLogger(RegistroDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           JFileChooser fc = new JFileChooser();
                int option = fc.showSaveDialog(Tabla1);
                if(option == JFileChooser.APPROVE_OPTION){
                    String filename = fc.getSelectedFile().getName(); 
                    String path = fc.getSelectedFile().getParentFile().getPath();

					int len = filename.length();
					String ext = "";
					String file = "";

					if(len > 12){
						ext = filename.substring(len-4, len);
					}

					if(ext.equals(".xls")){
						file = path + "\\" + filename; 
					}else{
						file = path + "\\" + filename + ".xls"; 
					}
					//toExcel
                                        ModeloExcel me = new ModeloExcel();
                                        me.Exportar(new File(file),Tabla1);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(WebLookAndFeel.class.getCanonicalName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEli;
    private javax.swing.JButton btnLimpiarCamp;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMod;
    private javax.swing.JTextField inputAI;
    private javax.swing.JTextField inputAM;
    private javax.swing.JTextField inputAP;
    private javax.swing.JTextField inputCE;
    private javax.swing.JTextField inputD;
    private javax.swing.JTextField inputFN;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputINC;
    private javax.swing.JTextField inputN;
    private javax.swing.JTextField inputNC;
    private javax.swing.JTextField inputNT;
    private javax.swing.JTextField inputTEC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
