/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import informeRetencion.CrudAntPer;

/**
 *
 * @author snahu
 */
public class seleccionDocentes extends javax.swing.JFrame {

    public static String user;
    public static String rut;

    /**
     * Creates new form seleccionDocentes
     */
    public seleccionDocentes() {
        initComponents();
        CargarTabla();
        this.lblOP.setVisible(false);
    }

    public void CargarTabla() {
        CrudAntPer Caa = new CrudAntPer();
        DefaultTableModel model = new DefaultTableModel();
        model = Caa.lista();
        tablaSeleccion.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeleccion = new javax.swing.JTable();
        btnSeleccion = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblOP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione Docente");

        tablaSeleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSeleccion);

        btnSeleccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/iconos/boton_modificar.png"))); // NOI18N
        btnSeleccion.setText("Seleccion");
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/iconos/boton_libro.png"))); // NOI18N
        btnMenu.setText("Volver al Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblOP.setText("op- oculta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lblOP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOP))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        dashboardAdmin frm = new dashboardAdmin();
        dashboardAdmin.user = this.user;
        dashboardAdmin.rut = this.rut;
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tablaSeleccion.getModel();
        int i = tablaSeleccion.getSelectedRow();
//condicion si no se selecciono ninguno
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un docente de la lista", "", 0);
        } else {
//mostramso los datos en los jtxt
            //convertimos en string el resultado
            if (this.lblOP.getText().equals("1")) {

                antecedentesLaborales ant = new antecedentesLaborales();
                ant.inputIDdoc.setText(String.valueOf(tablaSeleccion.getValueAt(i, 0)));
                ant.lblRut.setText("Rut: " + String.valueOf(tablaSeleccion.getValueAt(i, 1)));
                ant.lblNombreDoc.setText("Docente: " + String.valueOf(tablaSeleccion.getValueAt(i, 2) + " " + String.valueOf(tablaSeleccion.getValueAt(i, 3))));

                ant.setLocationRelativeTo(null);
                ant.setVisible(true);
                this.dispose();
            } else {
                if (this.lblOP.getText().equals("2")) {
                    AntecentesAcademicos ant = new AntecentesAcademicos();
                    ant.lblIDdoc.setText(String.valueOf(tablaSeleccion.getValueAt(i, 0)));
                    ant.lblRut.setText("Rut: " + String.valueOf(tablaSeleccion.getValueAt(i, 1)));
                    ant.lblDocNom.setText("Docente: " + String.valueOf(tablaSeleccion.getValueAt(i, 2) + " " + String.valueOf(tablaSeleccion.getValueAt(i, 3))));
                    ant.setLocationRelativeTo(null);
                    ant.setVisible(true);
                    this.dispose();
                } else {
                    if (this.lblOP.getText().equals("3")) {
                        RegistroDocenteDetalle regDet = new RegistroDocenteDetalle();
                        //regDet.lblIDdoc.setText(String.valueOf(tablaSeleccion.getValueAt(i, 0)));
                        regDet.setLocationRelativeTo(null);
                        regDet.setVisible(true);
                        this.dispose();
                    } else {
                        dashboardAdmin regDet = new dashboardAdmin();
                        //regDet.lblIDdoc.setText(String.valueOf(tablaSeleccion.getValueAt(i, 0)));
                        regDet.setLocationRelativeTo(null);
                        regDet.setVisible(true);
                        this.dispose();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionDocentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblOP;
    private javax.swing.JTable tablaSeleccion;
    // End of variables declaration//GEN-END:variables
}
